import 'package:flutter/material.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ColorModelOptions {
/*
{
  "label": "White",
  "value": "4"
} 
*/

  String? label;
  String? value;
  Color color = Colors.transparent;

  ColorModelOptions({
    this.label,
    this.value,
    required this.color,
  });
  ColorModelOptions.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    value = json['value']?.toString();
    color = getHex(json['label']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['value'] = value;
    return data;
  }

  Color getHex(String? name) {
    if (name == 'White') return Colors.white;
    if (name == "Black") return Colors.black;
    if (name == "Red") return Colors.red;
    if (name == "Blue") return Colors.blue;
    if (name == "Green") return Colors.green;
    if (name == "Beige") return Color(0xfff5f5dc);
    if (name == "Brass") return Color(0xffb5a642);
    if (name == "Brown") return Colors.brown;
    if (name == "Gold") return Color(0xffFFD700);
    if (name == "Grey") return Colors.grey;
    if (name == "Orange") return Colors.orange;
    if (name == "Pink") return Colors.pink;
    if (name == "Purple") return Colors.purple;
    if (name == "Silver") return Color(0xffC0C0C0);
    if (name == "Transparent") return Colors.transparent;
    if (name == "Yellow") return Colors.yellow;
    if (name == "Shimmer") return Color(0xffFFFEF7);
    if (name == "Bronze") return Color(0xffcd7f32);
    if (name == "Nude") return Color(0xffe3bc9a);
    return Colors.transparent;
  }
}

class ColorModel {
/*
{
  "options": [
    {
      "label": "White",
      "value": "4"
    }
  ]
} 
*/

  List<ColorModelOptions?>? options;

  ColorModel({
    this.options,
  });
  ColorModel.fromJson(Map<String, dynamic> json) {
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <ColorModelOptions>[];
      v.forEach((v) {
        if (v['label'].toString().trim() != '')
          arr0.add(ColorModelOptions.fromJson(v));
      });
      options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (options != null) {
      final v = options;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['options'] = arr0;
    }
    return data;
  }
}
