///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FabricModelOptions {
/*
{
  "label": " ",
  "value": ""
} 
*/

  String? label;
  String? value;

  FabricModelOptions({
    this.label,
    this.value,
  });
  FabricModelOptions.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['value'] = value;
    return data;
  }
}

class FabricModel {
/*
{
  "options": [
    {
      "label": " ",
      "value": ""
    }
  ]
} 
*/

  List<FabricModelOptions?>? options;

  FabricModel({
    this.options,
  });
  FabricModel.fromJson(Map<String, dynamic> json) {
  if (json['options'] != null) {
  final v = json['options'];
  final arr0 = <FabricModelOptions>[];
  v.forEach((v) {
  arr0.add(FabricModelOptions.fromJson(v));
  });
    options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (options != null) {
      final v = options;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['options'] = arr0;
    }
    return data;
  }
}
