///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MaterialModelOptions {
/*
{
  "label": " ",
  "value": ""
} 
*/

  String? label;
  String? value;

  MaterialModelOptions({
    this.label,
    this.value,
  });
  MaterialModelOptions.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['value'] = value;
    return data;
  }
}

class MaterialModel {
/*
{
  "options": [
    {
      "label": " ",
      "value": ""
    }
  ]
} 
*/

  List<MaterialModelOptions?>? options;

  MaterialModel({
    this.options,
  });
  MaterialModel.fromJson(Map<String, dynamic> json) {
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <MaterialModelOptions>[];
      v.forEach((v) {
        arr0.add(MaterialModelOptions.fromJson(v));
      });
      options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (options != null) {
      final v = options;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['options'] = arr0;
    }
    return data;
  }
}
