///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OccasionModelOptions {
/*
{
  "label": " ",
  "value": ""
} 
*/

  String? label;
  String? value;

  OccasionModelOptions({
    this.label,
    this.value,
  });
  OccasionModelOptions.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['value'] = value;
    return data;
  }
}

class OccasionModel {
/*
{
  "options": [
    {
      "label": " ",
      "value": ""
    }
  ]
} 
*/

  List<OccasionModelOptions?>? options;

  OccasionModel({
    this.options,
  });
  OccasionModel.fromJson(Map<String, dynamic> json) {
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <OccasionModelOptions>[];
      v.forEach((v) {
        arr0.add(OccasionModelOptions.fromJson(v));
      });
      options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (options != null) {
      final v = options;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['options'] = arr0;
    }
    return data;
  }
}
