///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TextureModelOptions {
/*
{
  "label": " ",
  "value": ""
} 
*/

  String? label;
  String? value;

  TextureModelOptions({
    this.label,
    this.value,
  });
  TextureModelOptions.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['value'] = value;
    return data;
  }
}

class TextureModel {
/*
{
  "options": [
    {
      "label": " ",
      "value": ""
    }
  ]
} 
*/

  List<TextureModelOptions?>? options;

  TextureModel({
    this.options,
  });
  TextureModel.fromJson(Map<String, dynamic> json) {
  if (json['options'] != null) {
  final v = json['options'];
  final arr0 = <TextureModelOptions>[];
  v.forEach((v) {
  arr0.add(TextureModelOptions.fromJson(v));
  });
    options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (options != null) {
      final v = options;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['options'] = arr0;
    }
    return data;
  }
}
